apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: vikashhembram/devops-platform-app
  newName: devopsplatformacr.azurecr.io/devops-platform-app
  newTag: da9d3da5505a24468cec8bc528ee44d4c84c10d7
