apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: vikashhembram/devops-platform-app
  newName: vikashhembram/devops-platform-app
  newTag: e78b8ddc6b76019c04ed09a3f874034aeb048f6b
