apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: vikashhembram/devops-platform-app
  newName: vikashhembram/devops-platform-app
  newTag: b98ccfa8443cf9252b3ed6a8008be9836c30c2ce
