name: GitOps

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-manifest:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tag
        run: |
          cd k8s/overlays/dev

          kustomize edit set image \
            vikashhembram/devops-platform-app=vikashhembram/devops-platform-app:${{ github.event.workflow_run.head_sha }}

      - name: Commit GitOps change
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add k8s/overlays/dev/kustomization.yml

          if git diff --cached --quiet; then
            echo "No GitOps changes detected."
          else
            git commit -m "gitops: update image to ${{ github.event.workflow_run.head_sha }}"
            git push origin HEAD:main
          fi
